# Documentação de apoio
# https://github.com/nextcloud/docker
# https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud
####
version: '3'

services:
  # nginx-proxy-manager
  # nginx:
  #   image: nginx
  #   container_name: ${NGINX_CONTAINER_NAME}
  #   hostname: ${NGINX_HOSTNAME}
  #   restart: unless-stopped
  #   environment:
  #     NEXTCLOUD_HOSTNAME: ${NEXTCLOUD_HOSTNAME}
  #     ONLYOFFICE_HOSTNAME: ${ONLYOFFICE_HOSTNAME}
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ~/files-server/configs/nginx.conf:/etc/nginx/nginx.conf
  #     - ~/files-server/data-docker/nextcloud:/var/www/html
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    hostname: nginx-proxy-manager
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      # - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s

    # Uncomment the next line if you uncomment anything in the section
    # environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ~/files-server/data-docker/nginx-proxy-manager/data:/data
      - ~/files-server/data-docker/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - ~/files-server/data-docker/nextcloud:/var/www/html
    depends_on:
      - data_base_npm
    networks:
      - npm-net

  data_base_npm:
    image: mariadb:latest
    container_name: ${MARIADB_CONTAINER_NAME}-npm
    hostname: ${MARIADB_HOSTNAME}-npm
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - ~/files-server/data-docker/data_base-nginx-proxy-manager:/var/lib/mysql
    networks:
      - npm-net
  # Nextcloud
  nextcloud:
    image: nextcloud:fpm
    container_name: ${NEXTCLOUD_CONTAINER_NAME}
    hostname: ${NEXTCLOUD_HOSTNAME}
    restart: unless-stopped
    environment:
      TZ: ${NEXTCLOUD_TIME_ZONE}

      # NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      # NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: "${NEXTCLOUD_TRUSTED_DOMAINS}"
      
      NEXTCLOUD_DATA_DIR: ${NEXTCLOUD_DATA_DIR}

      MYSQL_DATABASE: ${NEXTCLOUD_MYSQL_DATABASE}
      MYSQL_USER: ${NEXTCLOUD_MYSQL_USER}
      MYSQL_PASSWORD: ${NEXTCLOUD_MYSQL_PASSWORD}
      MYSQL_HOST: ${NEXTCLOUD_MYSQL_HOST}
    expose:
      - '80'
      - '9000'
    depends_on:
      - data_base
      - minIO-S3
      - nginx-proxy-manager
    volumes:
      - ~/files-server/data-docker/nextcloud:/var/www/html
      - ~/files-server/resources/:/var/www/resources
    networks:
      - nextcloud-net
      - npm-net
  
  data_base:
    image: mariadb:latest
    container_name: ${MARIADB_CONTAINER_NAME}
    hostname: ${MARIADB_HOSTNAME}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_MYSQL_DATABASE}
      MYSQL_USER: ${MARIADB_MYSQL_USER}
      MYSQL_PASSWORD: ${MARIADB_MYSQL_PASSWORD}
    volumes:
      - ~/files-server/data-docker/mariaDB:/var/lib/mysql
    networks:
      - nextcloud-net
  
  minIO-S3:
    image: minio/minio
    container_name: ${MINIO_CONTAINER_NAME}
    hostname: ${MINIO_HOSTNAME}
    restart: unless-stopped
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER} # AccessKey
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD} # SecretKey
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/servidor-s3/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    expose:
      - '9000'
      - '9001'
    volumes:
      - ~/files-server/data-docker/minIO:/data
    networks:
      - nextcloud-net
      - npm-net
  # Onlyoffice
  onlyoffice:
    image: onlyoffice/documentserver
    container_name: ${ONLYOFFICE_CONTAINER_NAME}
    hostname: ${ONLYOFFICE_HOSTNAME}
    restart: unless-stopped
    environment:
      JWT_SECRET: ${ONLYOFFICE_JWT_SECRET}
    expose:
      - '80'
      - '443'
    volumes:
      - ~/files-server/data-docker/onlyoffice/logs:/var/log/onlyoffice
      - ~/files-server/data-docker/onlyoffice/data:/var/www/onlyoffice/Data
      - ~/files-server/data-docker/onlyoffice/lib:/var/lib/onlyoffice
      - ~/files-server/data-docker/onlyoffice/postgresql:/var/lib/postgresql
    networks:
      - onlyoffice-net
      - nextcloud-net
      - npm-net

networks:
  onlyoffice-net:
    name: onlyoffice-net
  nextcloud-net:
    name: nextcloud-net
  npm-net:
    name: npm-net