# Documentação de apoio
# https://github.com/nextcloud/docker
# https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud
####
version: '3'

services:
  nextcloud:
    image: nextcloud:stable
    container_name: ${NEXTCLOUD_CONTAINER_NAME}
    hostname: ${NEXTCLOUD_HOSTNAME}
    restart: unless-stopped
    environment:
      TZ: ${NEXTCLOUD_TIME_ZONE}

      # NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      # NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: "${NEXTCLOUD_TRUSTED_DOMAINS}"
      
      NEXTCLOUD_DATA_DIR: ${NEXTCLOUD_DATA_DIR}

      MYSQL_DATABASE: ${NEXTCLOUD_MYSQL_DATABASE}
      MYSQL_USER: ${NEXTCLOUD_MYSQL_USER}
      MYSQL_PASSWORD: ${NEXTCLOUD_MYSQL_PASSWORD}
      MYSQL_HOST: ${NEXTCLOUD_MYSQL_HOST}
    expose:
      - '80'
      - '9000'
    depends_on:
      - data_base
      - minIO-S3
    volumes:
      - ~/files-server/data-docker/nextcloud:/var/www/html
      - ~/files-server/resources/:/var/www/resources
    networks:
      - nextcloud-net
      - npm-net
  
  data_base:
    image: mariadb:latest
    container_name: ${MARIADB_CONTAINER_NAME}
    hostname: ${MARIADB_HOSTNAME}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_MYSQL_DATABASE}
      MYSQL_USER: ${MARIADB_MYSQL_USER}
      MYSQL_PASSWORD: ${MARIADB_MYSQL_PASSWORD}
    volumes:
      - ~/files-server/data-docker/mariaDB:/var/lib/mysql
    networks:
      - nextcloud-net
  
  minIO-S3:
    image: minio/minio
    container_name: ${MINIO_CONTAINER_NAME}
    hostname: ${MINIO_HOSTNAME}
    restart: unless-stopped
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER} # AccessKey
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD} # SecretKey
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/servidor-s3/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ~/files-server/data-docker/minIO:/data
    networks:
      - nextcloud-net
      - npm-net

networks:
    nextcloud-net:
        name: nextcloud-net
    npm-net:
        external: true
        name: npm-net