# Documentação de apoio
# https://github.com/nextcloud/docker
# https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud
####
version: '3'

services:
  # nginx:
  #   image: nginx
  #   container_name: ${NGINX_CONTAINER_NAME}
  #   hostname: ${NGINX_HOSTNAME}
  #   restart: unless-stopped
  #   environment:
  #     NEXTCLOUD_HOSTNAME: ${NEXTCLOUD_HOSTNAME}
  #     ONLYOFFICE_HOSTNAME: ${ONLYOFFICE_HOSTNAME}
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ~/files-server/configs/nginx.conf:/etc/nginx/nginx.conf
  #     - ~/files-server/data-docker/nextcloud:/var/www/html
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    hostname: nginx-proxy-manager
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      # - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s

    # Uncomment the next line if you uncomment anything in the section
    # environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ~/files-server/data-docker/nginx-proxy-manager/data:/data
      - ~/files-server/data-docker/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    depends_on:
      - data_base_npm
    networks:
      - npm-net

  data_base_npm:
    image: mariadb:latest
    container_name: ${MARIADB_CONTAINER_NAME}-npm
    hostname: ${MARIADB_HOSTNAME}-npm
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - ~/files-server/data-docker/data_base-nginx-proxy-manager:/var/lib/mysql
    networks:
      - npm-net

networks:
  npm-net:
    name: npm-net